# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Dirver
    url: jdbc:mysql://localhost:3306/db_board?serverTimezone=UTC&characterEncoding=UTF-8
    username: user_sohee
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml